begin;

alter table public.site_state enable row level security;
drop policy if exists "Allow public upsert site_state" on public.site_state;
drop policy if exists "Allow public update site_state" on public.site_state;
revoke insert, update, delete on public.site_state from anon, authenticated;

create table if not exists public.contact_inquiries (
  id uuid primary key,
  name text not null,
  company text not null,
  contact text not null,
  service text,
  message text,
  source text not null default 'homepage-contact',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  visitor_id uuid not null default gen_random_uuid(),
  visitor_name text,
  visitor_email text,
  company_name text,
  status text not null default 'active'
    check (status in ('active', 'completed', 'abandoned', 'blocked')),
  topic text,
  summary text,
  openai_conversation_id text,
  user_message_count integer not null default 0 check (user_message_count >= 0),
  input_tokens bigint not null default 0 check (input_tokens >= 0),
  output_tokens bigint not null default 0 check (output_tokens >= 0),
  estimated_cost_usd numeric(12, 6) not null default 0 check (estimated_cost_usd >= 0),
  consented_at timestamptz,
  last_active_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz
);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  moderation_status text not null default 'allowed'
    check (moderation_status in ('allowed', 'blocked', 'review')),
  moderation_reason text,
  openai_response_id text,
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.chat_files (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  message_id uuid references public.chat_messages(id) on delete set null,
  original_name text not null,
  storage_path text not null unique,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor text not null,
  action text not null,
  target_type text not null,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists chat_sessions_created_at_idx on public.chat_sessions (created_at desc);
create index if not exists chat_sessions_status_idx on public.chat_sessions (status, last_active_at desc);
create index if not exists chat_messages_session_created_idx on public.chat_messages (session_id, created_at);
create index if not exists chat_files_session_idx on public.chat_files (session_id);
create index if not exists admin_audit_logs_created_at_idx on public.admin_audit_logs (created_at desc);

alter table public.contact_inquiries enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.chat_files enable row level security;
alter table public.admin_audit_logs enable row level security;

revoke all on public.contact_inquiries from anon, authenticated;
revoke all on public.chat_sessions from anon, authenticated;
revoke all on public.chat_messages from anon, authenticated;
revoke all on public.chat_files from anon, authenticated;
revoke all on public.admin_audit_logs from anon, authenticated;

commit;
